modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="ktmresource"
version="${file.jarVersion}"
displayName="KTM Resource"
logoFile="logo.png"
credits="Kzeroko, Qma_Feng, xiao_lanovo"
authors="Kzeroko"
description='''
This mod will add custom resources such as weapons, items, fluids, foods and blocks
that integrates mods in modpack KTM:PhantasmReality 1.18.2 Ver.
Which is a sequel to modpack KTM
Interesting Fact: KTM=KenToMahou
(Many of the features/contents are not implemented yet)
'''

[[dependencies.ktmresource]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ktmresource]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[modproperties.ktmresource]
    catalogueImageIcon="icon.png"