modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="ktmresource"
version="${file.jarVersion}"
displayName="KTM Resource"
logoFile="logo.png"
credits="Kzeroko, Qma_Feng, xiao_lanovo, Xiu_Jia"
authors="Kzeroko, Qma_Feng"
description='''
Custom items, blocks and fluids for modpack KTM:PhantasmReality
Which is a sequel to modpack KTM

KTM=KenToMahou (Swords and Magic)
* Many of the features/contents are not implemented yet *
'''

[[dependencies.ktmresource]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ktmresource]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ktmresource]]
    modId="epicfight"
    mandatory=true
    versionRange="[18.3.1,18.4.0)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.ktmresource]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.1.2,)"
    ordering = "AFTER"
    side = "BOTH"

[modproperties.ktmresource]
    catalogueImageIcon="icon.png"